import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

// Define local fonts with the correct path
const geistSans = localFont({
  src: "/fonts/GeistVF.woff",  // Ensure this path is correct
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "/fonts/GeistMonoVF.woff",  // Ensure this path is correct
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the document
export const metadata = {
  title: "First Practice",
  description: "Generated by create next app",
};

// Root layout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Add Font Awesome CDN link */}
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
          rel="stylesheet"
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <Navbar/>
        {children}
      <Footer/>
      </body>
    </html>
  );
}
